# Generated by Django 5.1.6 on 2025-03-05 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='is_unread',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookmarks_in_collection', to='delish.collection'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bookmarks_with_tag', to='delish.tag'),
        ),
    ]
