# Generated by Django 5.1.7 on 2025-03-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delish', '0002_bookmark_is_unread_alter_bookmark_collection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['timestamp']},
        ),
    ]
