# Generated by Django 5.1.7 on 2025-03-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delish', '0007_alter_bookmark_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(),
        ),
    ]
