POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "antonio", "password": "pass1234!"}

###

POST http://127.0.0.1:8000/register
Content-Type: application/json

{"username": "antonio", "password": "pass1234!", "email": "antonio@mail.com"}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 0c86908ef00ce6fde8f6d0dbf6da5f7efd9eeadd

{}

