# Generated by Django 5.1.7 on 2025-03-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delish', '0003_alter_bookmark_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='user',
            new_name='owner',
        ),
    ]
