# Generated by Django 5.1.7 on 2025-03-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delish', '0004_rename_user_bookmark_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
