# Generated by Django 5.1.7 on 2025-03-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delish', '0009_alter_bookmark_description_alter_bookmark_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
