###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json
Credentials: "include"

{
  "username": "admin",
  "password": "arigato80"
}

###

POST http://localhost:8000/api/token/refresh HTTP/1.1
Content-Type: application/json
Credentials: "include"

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NTU4NjUyMCwiaWF0IjoxNzQyOTk0NTIwLCJqdGkiOiJjMDNlODY2ZmI5ODQ0MTlkOTk3ZjdjZTFmM2JjYjYwYiIsInVzZXJfaWQiOjIsInVzZXJuYW1lIjoidXNlcjEifQ.jp1ylRo12a89LzO_QdPuPTthLKsYLq_1jxvCY2Edu-8"
}

###

POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{ "username": "user1", "password": "password" }

###

POST http://localhost:8000/register HTTP/1.1
Content-Type: application/json

{ "username": "antonio", "password": "pass1234!", "email": "antonio@mail.com" }

###

GET http://localhost:8000/bookmarks/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyNjUzMTM0LCJpYXQiOjE3NDI2NTI4MzQsImp0aSI6ImJkOGRlN2NmYTA1MjQyZTI4YzYyZjYwYzczMzdhMjc0IiwidXNlcl9pZCI6MX0.L0trzWXhemQd_nIxhuQOPk4589TtKHH2PngTh7czzlI

###

POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{ "username": "admin", "password": "arigato80" }
